#!/bin/bash
export LANG=de_DE.UTF-8

function confline # get first line from file $1 mathing $2, stripped of # and ; comment lines, stripped spaces and tabs down to spaces, remove trailing ;
 {
  echo $(cat $1|grep -v '^$\|^\s*\#'|sed -e "s/[[:space:]]\+/ /g"|sed s/^\ //|sed s/\;//|grep -i "$2"|head -n 1)
 }

fastdconf=( "/etc/fastd/sn4/main.conf" )
BATCTL=$(confline $fastdconf //\ batctl|cut -d ' ' -f 3)
MINPEERS=$(confline $fastdconf //\ minpeers|cut -d ' ' -f 3)
MAXPEERS=$(confline $fastdconf peer\ limit|cut -d ' ' -f 3)
BUFFERPERCENTAGE=$(confline $fastdconf //\ bufferpercentage|cut -d ' ' -f 3)

for i in ${fastdconf[@]}
do
  net_peer_amount=$($BATCTL o |wc -l)
  peerlimit=$(grep -oP '(?<=^peer\slimit\s)[0-9]+(?=\s*;$)' ${i})
  gwamount=$(($($BATCTL gwl -H |wc -l)-1))
  connection_average_estimate=$(( net_peer_amount / gwamount ))
  connection_limit_estimate=$((connection_average_estimate + (connection_limit_estimate * BUFFERPERCENTAGE)/100))

  if [ $peerlimit -gt $connection_limit_estimate ]; then

    [ $connection_limit_estimate -le $MINPEERS ] && connection_limit_estimate=$MINPEERS
    [ $connection_limit_estimate -ge $MAXPEERS ] && connection_limit_estimate=$MAXPEERS

    sed -i "s/peer limit [0-9]*;/peer limit $connection_limit_estimate;/" ${i}
    pkill -HUP -x fastd
  fi

done
